### PR TITLE
Fix sync cart between tabs

### LINKED ISSUE #3838: Sync cart between tabs
## Current behavior

Let's imagine a typical e-commerce scenario. I am opening the category's view and browsing stuff. Then I am opening a few product's views in new carts. I jump to the first product and adding it to cart then in other tab I am adding to the cart another product. In the end, I am again in tab with the category's view. I refresh and... I have only one product in the cart - but I should have 2.

## Expected behavior

When I am adding to the cart in one tab I have sync in other tabs for the cart.

## Steps to reproduce the issue

In description..

## Repository

You can do test here: https://demo.vuestorefront.io/

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Chrome
- OS:  Ubuntu 16.04
- Node: 
- Code Version: 

## Additional information

Maybe it could be helpful: https://github.com/xanf/vuex-shared-mutations

### PR DESCRIPTION
**Pull request by Michal-Dziedzinski**
### Related Issues

closes #3838 

### Short Description and Why It's Useful

Fix sync cart between tabs using localStorage

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/themes/default/components/core/blocks/Header/MicrocartIcon.vue [hunk 1]
```diff
@@ -25,11 +25,7 @@ import MicrocartIcon from '@vue-storefront/core/compatibility/components/blocks/
 export default {
   // mixins: [MicrocartIcon],
   mounted () {
-    document.addEventListener('visibilitychange', () => {
-      if (!document.hidden) {
-        this.$store.dispatch('cart/load')
-      }
-    })
+    window.addEventListener('storage', this.getItemsFromStorage)
```
Comment (gibkigonzo) [inline src/themes/default/components/core/blocks/Header/MicrocartIcon.vue]: wdyt about moving all of this logic to mounted? It's easier to read code (everything is in one place) and we don't need to add method to component
```
    const getItemsFromStorage =...
    window.addEventListener('storage', getItemsFromStorage)
    this.$once('hook:destroyed', () => {
      window.removeEventListener('storage', getItemsFromStorage)
    })
```

Comment (andrzejewsky) [reply src/themes/default/components/core/blocks/Header/MicrocartIcon.vue]: I think `beforeDestroy` it's even dedicated place to removing event listeners.

Comment (Michal-Dziedzinski) [reply src/themes/default/components/core/blocks/Header/MicrocartIcon.vue]: I moved the functions to a separate file. Thanks for the suggestions!
