### PR TITLE
Remove login dialog when you logged out using button from sidebar menu

### LINKED ISSUE #3680: Login components shows up after Logging out
## Current behavior
Login component pops up when it should not. It shows in some cases when **logging out**.

## Expected behavior
After logout no Login component shows up.

## Steps to reproduce the issue
1. Log in
2. Open left SidebarMenu
3. Navigate to "My Account"
4. Click Log out in this menu
5. Now Login components Popup. It is propably fired because router treis to navigate to protected route /my-acount when logging out.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [X] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 77
- OS: LInux, Ubuntu 18

## Additional information
When removing commiting "ui/setSubmenu" from afterRegistration function in [afterRegistration.ts](https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/user/hooks/afterRegistration.ts) it works fine, but there could be some side effects of deleting this code.

### PR DESCRIPTION
**Pull request by andrzejewsky**
### Related issues
closes #3680

### Which environment this relates to
- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/themes/default/components/core/blocks/SidebarMenu/SubCategory.vue [hunk 1]
```diff
@@ -144,7 +144,7 @@ export default {
   },
   methods: {
     logout () {
-      this.$bus.$emit('user-before-logout')
+      this.$store.dispatch('user/logout', {})
```
Comment (patzick) [inline src/themes/default/components/core/blocks/SidebarMenu/SubCategory.vue]: couldn't be just
```suggestion
      this.$store.dispatch('user/logout')
```
?
Accepting either way :)

Comment (andrzejewsky) [reply src/themes/default/components/core/blocks/SidebarMenu/SubCategory.vue]: it causes error because of https://github.com/DivanteLtd/vue-storefront/blob/develop/core/modules/user/store/actions.ts#L213 (requires object)
