### PR TITLE
[3053] Fixed memory leak with enabled dynamicConfigReload.

### LINKED ISSUE #3053: Memory leaks related to dynamicConfigReload option.
## Current behavior
We see potencial memory leaks on SSR level.

## Expected behavior
GC clean unused memory segments.

## Steps to reproduce the issue
If setup `dynamicConfigReload` to `true` in production mode we see leak of memory
And use `autocannon` for example.
http://dimasch.github.io/yandex-tank-benchmark/

## Repository
Affected all version and branches.

`core/scripts/server.js`

Possible workaround:
```
if (config.server.dynamicConfigReload) {
    const cachedConfigModule = require.cache[require.resolve('config')]
    if (cachedConfigModule) {
      delete cachedConfigModule.parent.children;
      delete cachedConfigModule;
    }
```

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by dimasch**
### Related issues
closes #3053

### Screenshots of visual changes before/after (if there are any)

After stress test GC corrected flush memory usage:

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
Thanks @dimasch however there is a problem with eslint causing CI to fail: 

```
/home/travis/build/DivanteLtd/vue-storefront/core/scripts/server.js
  252:7  error  Variables should not be deleted  no-delete-var
```

Please fix it - even by adding the [ignore](https://stackoverflow.com/questions/27732209/turning-off-eslint-rule-for-a-specific-line)

File: core/scripts/server.js [hunk 1]
```diff
@@ -246,7 +246,11 @@ app.get('*', (req, res, next) => {
   }
 
   if (config.server.dynamicConfigReload) {
-    delete require.cache[require.resolve('config')]
+    const cachedConfigModule = require.cache[require.resolve('config')]
+    if (cachedConfigModule) {
+      delete cachedConfigModule.parent.children
+      delete cachedConfigModule
```
Comment (patzick) [inline core/scripts/server.js]: Variables should not be deleted, only properties of object, i'd suggest:
```suggestion
      delete require.cache[require.resolve('config')]
```

**Comment by pkarw** [comment]
@dimasch you missed the changelog update - please add a line on this fix there and we're merging this in :)
