### PR TITLE
fix(ayc): addToCart will add product rather than update qty

### LINKED ISSUE #4438: Problem with updating the quantity of products in the cart
## Current behavior
Quantity of added products is not updated correctly.

## Expected behavior
The right quantity of product should be in the basket. Previous Qty should be updated.

## Steps to reproduce the issue
1. Go to any PDP
2. Set qty = 5
3. Add to cart
4. Change qty to 3 and add to cart again

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by lukeromanowicz**
closes #4438

### CODE REVIEW

File: packages/about-you/composables/src/composables/useCart/factoryParams.ts [hunk 1]
```diff
@@ -47,11 +47,7 @@ export const params: UseCartFactoryParams<BasketResponseData, BasketItem, BapiPr
   addToCart: async ({ currentCart, product, quantity }) => {
```
Comment (krskibin) [inline packages/about-you/composables/src/composables/useCart/factoryParams.ts:47]: WDYT about that?
```suggestion
  addToCart: async ({ currentCart, product, quantity=1 }) => {
```
