### PR TITLE
Fix adding unconfigured products to compare & optimize fetching homepage data

### LINKED ISSUE #3293: It is possible to add unconfigured product to wishlist
## Current behavior

The product added from the home page to the wish list from the product tile is unconfigured.

wishlist

## Expected behavior

The product added from the home page to the wish list from the product tile is configured the same as added from the category page.

wishlit--corect

## Repository

develop

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Code Version: develop:latest

### PR DESCRIPTION
**Pull request by lukeromanowicz**
fix adding unconfigured products to compare, optimize fetching data on homepage, remove unused cool bags code

### Related issues

closes #3293

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

File: src/themes/default/store/homepage.ts [hunk 1]
```diff
@@ -1,6 +1,29 @@
+import {prepareQuery} from '@vue-storefront/core/modules/catalog/queries/common'
+
 export const homepageStore = {
   namespaced: true,
   state: {
     new_collection: []
+  },
+  actions: {
+    fetchNewCollection ({ commit, dispatch }) {
```
Comment (patzick) [inline src/themes/default/store/homepage.ts]:
```suggestion
    async fetchNewCollection ({ commit, dispatch }) {
```

File: src/themes/default/store/homepage.ts [hunk 2]
```diff
@@ -1,6 +1,29 @@
...
+      const newProductsQuery = prepareQuery({ queryConfig: 'newProducts' })
+
+      dispatch('product/list', {
```
Comment (patzick) [inline src/themes/default/store/homepage.ts]: please just change this to async/await

File: src/themes/default/pages/Home.vue [hunk 3]
```diff
@@ -70,9 +66,6 @@ export default {
     everythingNewCollection () {
       return this.$store.state.homepage.new_collection
```
Comment (patzick) [inline src/themes/default/pages/Home.vue]: would be perfect to add a getter for newCollection in store and use it here:)

File: src/themes/default/store/homepage.ts (hunk 2 above)
Comment (lukeromanowicz) [reply src/themes/default/store/homepage.ts]: @patzick awaits are usually slower, that's why I avoid them. Dispatch should be returned though, I give you that.

File: src/themes/default/pages/Home.vue (hunk 3 above)
Comment (lukeromanowicz) [reply src/themes/default/pages/Home.vue]: Right :+1:  I guess I can refactor that part as well.

File: src/themes/default/store/homepage.ts (hunk 2 above)
Comment (filrak) [reply src/themes/default/store/homepage.ts]: I also would like to see such studies since all I ever read was saying it's still a microtask under the hood and just syntax sugar for Promises ;)

It can be slower only if you don't know how it works (not concurrently) and expect multiple await to run simultaneously but it's exactly the same with Promises

Comment (filrak) [reply src/themes/default/store/homepage.ts]: @patzick https://v8.dev/blog/fast-async it was this one
