### PR TITLE
Next: Token in sessionStorage & removing onUnmounted

### LINKED ISSUE #4928: CKO - Better card token handling
## Current behavior

We are storing card/instrument token inside localStorage.

## Expected behavior

We should store it in sessionStorage and remove it if someone leaves checkout.

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Todo

- [ ] localStorage -> sessionStorage
- [ ] remove stored token in onUnmounted

### PR DESCRIPTION
**Pull request by Fifciu**
### Related Issues

closes #4928

### Short Description and Why It's Useful

Storing payment token in sessionStorage and removing it in `onUnmounted`

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by andrzejewsky — APPROVED** [review]

File: packages/checkout-com/src/useCkoCard.ts [hunk 1]
```diff
@@ -113,6 +113,8 @@ const useCkoCard = (selectedPaymentMethod: Ref<CkoPaymentType>) => {
     selectedPaymentMethod.value = CkoPaymentType.SAVED_CARD;
   };
 
+  onUnmounted(removeTransactionToken);
```
Comment (EugeneHlushko) [inline packages/checkout-com/src/useCkoCard.ts:116]: Can you clarify when this gets triggered?

Comment (Fifciu) [reply packages/checkout-com/src/useCkoCard.ts]: You were right. I made changes. Since now you will have to append this logic manually in your app - I added bullet about this to the readme

**Review by andrzejewsky — APPROVED** [review]
