### PR TITLE
Wishlist SSR Core - Fix

### LINKED ISSUE #5076: Wishlist does not support SSR
## Current behavior

Wishlist core factory does not support SSR. It is caused by bad scope of sharedRefs.

## Expected behavior

It should properly convey fetched data from server to the client without need to refetch

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

### PR DESCRIPTION
**Pull request by Fifciu**
### Related Issues

closes #5076

### Short Description and Why It's Useful

Fixes the problem and unlocks Wishlist CT Enterprise extension

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [ ] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by andrzejewsky — APPROVED** [review]

File: packages/core/core/src/factories/useWishlistFactory.ts [hunk 1]
```diff
@@ -66,9 +66,10 @@ export const useWishlistFactory = <WISHLIST, WISHLIST_ITEM, PRODUCT>(
     const loadWishlist = async (customQuery?: CustomQuery) => {
       Logger.debug('useWishlist.loadWishlist');
 
+      loading.value = true;
```
Comment (lukasborawski) [inline packages/core/core/src/factories/useWishlistFactory.ts:69]: Maybe it's insignificant, but what for invoke loading if you already have a wishlist? 

```suggestion
      if (wishlist.value) return;
      loading.value = true;
```

**Review by lukasborawski — APPROVED** [review]

File: packages/core/core/src/factories/useWishlistFactory.ts (hunk 1 above)
Comment (filrak) [reply packages/core/core/src/factories/useWishlistFactory.ts:69]: we had discussions about this with @andrzejewsky and as far as I remember we decided that it's better to leave it like this to avoid confusion with debugging

you can do similar in your code:

```js
onSSR(async () {
 if (wishlist.value) await loadWishlist()
})
```

Comment (Fifciu) [reply packages/core/core/src/factories/useWishlistFactory.ts:69]: Removed it

**Review by filrak — APPROVED** [review]
