### PR TITLE
remove infinite loop after changing checkbox in shipping details

### LINKED ISSUE #3656: VSF freezes after selecting the checkbox "Use my company's address details".
## Current behavior
VSF freezes after selecting the checkbox "Use my company's address details"

## Expected behavior
Company address details should be copied.

## Steps to reproduce the issue
1. Log in
2. Go to My Account
3. Switch to My shipping details tab
4. Press _Edit your shipping details_ 
5. Select the checkobox _Use my company's address details_ 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by gibkigonzo**
### Related issues

closes #3656

### Short description and why it's useful

This fixes infinite loop witch shows up after switching between company address and shipping address in shipping details.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: core/modules/user/components/UserShippingDetails.ts [hunk 1]
```diff
@@ -132,13 +125,8 @@ export const UserShippingDetails = {
...
       this.useCompanyAddress = !this.useCompanyAddress
       if (this.useCompanyAddress) {
-        let index
-        for (let i = 0; i < this.currentUser.addresses.length; i++) {
-          if (toString(this.currentUser.addresses[i].id) === toString(this.currentUser.default_billing)) {
-            index = i
-          }
-        }
-        if (index >= 0) {
+        const index = this.currentUser.addresses.findIndex((address) => toString(address.id) === toString(this.currentUser.default_billing))
```
Comment (filrak) [inline core/modules/user/components/UserShippingDetails.ts]: why not just find() in condition statement? seems clener https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Obiekty/Array/find

Comment (gibkigonzo) [reply core/modules/user/components/UserShippingDetails.ts]: good point :) changed

File: core/modules/user/components/UserShippingDetails.ts [hunk 2]
```diff
@@ -132,21 +125,16 @@ export const UserShippingDetails = {
     fillCompanyAddress () {
       this.useCompanyAddress = !this.useCompanyAddress
```
Comment (andrzejewsky) [inline core/modules/user/components/UserShippingDetails.ts]: just delete this line, that's the fix 😄 try!
Deleting all this watch, can break something I think, look here: https://github.com/DivanteLtd/vue-storefront/blob/273ab206c0b6733ee10c4fb53188f79289769519/core/modules/user/components/UserShippingDetails.ts#L118

Comment (gibkigonzo) [reply core/modules/user/components/UserShippingDetails.ts]: Yes, that's the fix :) I wanted to remove `watch` as it is I think less predictable. You are right that this can break something so I've changed it.
