### PR TITLE
Bugfix/3150

### LINKED ISSUE #3150: AddToCart button becomes grey out when endpoint is broken
## Current behavior
AddToCart becomes grey out when endpoint is broken
image

## Expected behavior
Despite that endpoint  is broken, AddToCart button should be active and an error message should be displayed. (e.g. Something went wrong ...)

## Steps to reproduce the issue
1. Broke "updateitem_endpoint": "https://demo.storefrontcloud.io/api/cart/update
2. Go to product page
3. Try to Add to cart

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by pkarw**
### Related issues

closes #3150

Fix for #3150, Added `is_result_cacheable` for Task.ts in case of stock checks (that should be cached for Checkout.js doublecheck) - all other tasks should be removed from storage after execution

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### CODE REVIEW

File: core/modules/catalog/store/stock/actions.ts [hunk 1]
```diff
@@ -33,6 +33,27 @@ const actions: ActionTree<StockState, RootState> = {
       }
     })
   },
+  /**
+   * Reset current configuration and selected variatnts
+   */
+  check (context, { product, qty = 1 }) {
```
Comment (patzick) [inline core/modules/catalog/store/stock/actions.ts]: would be a lot more readable with async/await syntax

File: core/modules/catalog/store/stock/actions.ts [hunk 2]
```diff
@@ -33,6 +33,27 @@ const actions: ActionTree<StockState, RootState> = {
...
+    return new Promise((resolve, reject) => {
+      if (config.stock.synchronize) {
+        TaskQueue.execute({ url: config.stock.endpoint + '/check?sku=' + encodeURIComponent(product.sku),
```
Comment (patzick) [inline core/modules/catalog/store/stock/actions.ts]:
```suggestion
        TaskQueue.execute({ url: processURLAddress(`${config.stock.endpoint}/check?sku=${encodeURIComponent(product.sku)}),
```

File: core/modules/cart/components/AddToCart.ts [hunk 3]
```diff
@@ -20,13 +21,31 @@ export const AddToCart = {
...
+      try {
+        const diffLog = await this.$store.dispatch('cart/addItem', { productToAdd: product })
+        if (diffLog) {
+          if (diffLog.clientNotifications && diffLog.clientNotifications.length > 0) {
+            diffLog.clientNotifications.forEach(notificationData => {
+              this.$store.dispatch('notification/spawnNotification', notificationData, { root: true })
+            })
+          }
+        } else {
+          this.$store.dispatch('notification/spawnNotification', {
```
Comment (patzick) [inline core/modules/cart/components/AddToCart.ts]: IMO this method should return Boolean, and theme component should decide how to notify user, with notification. Another way to do this is to override this whole method in theme and it complicated further version updates

File: core/modules/cart/components/AddToCart.ts [hunk 4]
```diff
@@ -20,13 +21,33 @@ export const AddToCart = {
...
+        if (diffLog) {
+          if (diffLog.clientNotifications && diffLog.clientNotifications.length > 0) {
+            diffLog.clientNotifications.forEach(notificationData => {
+              this.notifyUser(notificationData)
+            })
+          }
+        } else {
+          this.notifyUser({
+            type: 'success',
+            message: i18n.t('Product has been added to the cart!'),
```
Comment (patzick) [inline core/modules/cart/components/AddToCart.ts]:
```suggestion
            message: this.$t('Product has been added to the cart!'),
```

File: core/modules/cart/components/AddToCart.ts [hunk 5]
```diff
@@ -1,4 +1,5 @@
 import Product from '@vue-storefront/core/modules/catalog/types/Product'
+import i18n from '@vue-storefront/i18n'
```
Comment (patzick) [inline core/modules/cart/components/AddToCart.ts]:
```suggestion
```

File: core/modules/cart/components/AddToCart.ts [hunk 6]
```diff
@@ -20,13 +21,33 @@ export const AddToCart = {
...
+          if (diffLog.clientNotifications && diffLog.clientNotifications.length > 0) {
+            diffLog.clientNotifications.forEach(notificationData => {
+              this.notifyUser(notificationData)
+            })
+          }
+        } else {
+          this.notifyUser({
+            type: 'success',
+            message: i18n.t('Product has been added to the cart!'),
+            action1: { label: i18n.t('OK') },
```
Comment (patzick) [inline core/modules/cart/components/AddToCart.ts]:
```suggestion
            action1: { label: this.$t('OK') },
```

File: core/modules/cart/components/AddToCart.ts [hunk 7]
```diff
@@ -20,13 +21,33 @@ export const AddToCart = {
...
+            action2: null
+          })
+        }
+        return diffLog
+      } catch (err) {
+        this.notifyUser({
+          type: 'error',
+          message: err,
+          action1: { label: i18n.t('OK') }
```
Comment (patzick) [inline core/modules/cart/components/AddToCart.ts]:
```suggestion
          action1: { label: this.$t('OK') }
```
