### PR TITLE
Bugfix - #2898

### LINKED ISSUE #2898: Products removed from the cart in the offline mode are re-added to the cart after going back to online mode
## Current behavior

Products removed from the cart in the offline mode are re-added to the cart after going back to online mode
Peek 2019-05-14 13-09

## Expected behavior

Products removed from the cart in the offline mode are not re-added to the cart after going back to online mode. The customer sees the same cart state as in offline mode. 

## Steps to reproduce the issue

1. Go to https://demo.storefrontcloud.io
2. Go to any product page
3. Add a few products to the cart
4. Switch to the offline mode
5. Remove some of the products from the cart
6. Switch back to the online mode
7. Check your cart 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Ubuntu 18.04 LTS

### PR DESCRIPTION
**Pull request by pkarw**
### Related issues

closes #2898

### Short description and why it's useful

I've changed the `forceClientState` = `true` in case the network mode changed. Now - the client's state cart is pushed and forced to the server when user is entering back the online mode

### Which environment this relates to

Not deployed, please do check on local branch.

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

File: core/modules/cart/store/actions.ts [hunk 1]
```diff
@@ -179,7 +179,7 @@ const actions: ActionTree<CartState, RootState> = {
       return task
     })
   },
-  load (context) {
+  load (context, cartLoadOptions: { forceClientState: boolean } = { forceClientState: true }) {
```
Comment (patzick) [inline core/modules/cart/store/actions.ts]:
```suggestion
  load (context, { forceClientState = true }:{forceClientState?:boolean} = {}) {
```

File: core/modules/cart/store/actions.ts [hunk 2]
```diff
@@ -204,7 +204,7 @@ const actions: ActionTree<CartState, RootState> = {
               commit(types.CART_LOAD_CART_SERVER_TOKEN, token)
               Logger.info('Cart token received from cache.', 'cache', token)()
               Logger.info('Pulling cart from server.','cart')()
-              context.dispatch('serverPull', { forceClientState: false, dryRun: !config.cart.serverMergeByDefault })
+              context.dispatch('serverPull', { forceClientState: cartLoadOptions.forceClientState, dryRun: !config.cart.serverMergeByDefault })
```
Comment (patzick) [inline core/modules/cart/store/actions.ts]:
```suggestion
              context.dispatch('serverPull', { forceClientState, dryRun: !config.cart.serverMergeByDefault })
```

File: core/modules/offline-order/helpers/onNetworkStatusChange.ts [hunk 3]
```diff
@@ -10,8 +10,7 @@ export function onNetworkStatusChange (store) {
 
   if (typeof navigator !== 'undefined' && navigator.onLine) {
     EventBus.$emit('sync/PROCESS_QUEUE', { config: config }) // process checkout queue
-    store.dispatch('cart/load')
-
+    store.dispatch('cart/load', { forceClientState: true })
```
Comment (patzick) [inline core/modules/offline-order/helpers/onNetworkStatusChange.ts]: shouldn't be changed if default value is `true`
```suggestion
    store.dispatch('cart/load')
```

File: core/pages/Checkout.js [hunk 4]
```diff
@@ -62,7 +62,7 @@ export default {
     this.$bus.$on('checkout-after-shippingMethodChanged', this.onAfterShippingMethodChanged)
     this.$bus.$on('checkout-after-validationError', this.focusField)
     if (!this.isThankYouPage) {
-      this.$store.dispatch('cart/load').then(() => {
+      this.$store.dispatch('cart/load', { forceClientState: true }).then(() => {
```
Comment (patzick) [inline core/pages/Checkout.js]: shouldn't be changed if default value is `true`
```suggestion
      this.$store.dispatch('cart/load').then(() => {
```

**Comment by patzick** [comment]
Thanks @pkarw! :)
