### PR TITLE
Fixes bug that caused addToCart action not to display messages to user

### LINKED ISSUE #4185: AddToCart component receiving wrong diffLog on very first call
## Current behavior

1. Open a new incognito window (must have completely clean state!)
2. Add a product to the cart
3. Expectation is that [addToCart](https://github.com/DivanteLtd/vue-storefront/blob/v1.11.2/src/themes/default/components/core/AddToCart.vue#L33-L35) method in the the `AddToCart.vue` component receives the `diffLog` produced by the request
4. However the entries in the received `diffLog` are empty:
    ```
    items: Array(0)
        length: 0
    serverResponses: Array(0)
        length: 0
    clientNotifications: Array(0)
        length: 0
    ```
5. On the following calls the `diffLog` has the correct data.

## Expected behavior

The `diffLog` should contain the details, i.e:

```
items: Array(3)
    0: {party: "server", sku: "866550", status: "no-item"}
    1: {party: "client", status: "no-changes"}
    2: {party: "server", status: "no-changes"}
    length: 3
serverResponses: Array(1)
    0: {status: 200, sku: "866550", result: {…}}
    length: 1
clientNotifications: Array(0)
    length: 0
```

I think the problem happens because on the very first time the sync happens through the [create action](https://github.com/DivanteLtd/vue-storefront/blob/v1.11.2/core/modules/cart/store/actions/itemActions.ts#L83
) instead of the [sync  action](https://github.com/DivanteLtd/vue-storefront/blob/v1.11.2/core/modules/cart/store/actions/itemActions.ts#L85)

However, the `create` call does not return any diffLog. I believe the fix would be to return the result here: https://github.com/DivanteLtd/vue-storefront/blob/v1.11.2/core/modules/cart/store/actions/connectActions.ts#L72

And then process that result (use `diffLog.merge()`?) in order to return the correct data to the `AddToCart` component.

I do not fully understand how all the cart related features work together, so could someone confirm whether my suggestion makes sense?

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

### PR DESCRIPTION
**Pull request by juho-jaakkola**
### Related Issues

closes #4185 

### Short Description and Why It's Useful

The very first time something was added to the cart, the user did not see any messages
("Added to cart", "n items need to be backordered", etc). These were displayed only
on the following times. This commit fixes it so that the messages are displayed also
on the very first action call.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: core/modules/cart/store/actions/itemActions.ts [hunk 1]
```diff
@@ -80,9 +80,18 @@ const itemActions = {
...
-    await dispatch('create')
+
+    let newDiffLog = await dispatch('create')
+    if (newDiffLog !== undefined) {
+      diffLog.merge(newDiffLog)
+    }
+
     if (getters.isCartSyncEnabled && getters.isCartConnected && !forceServerSilence) {
-      return dispatch('sync', { forceClientState: true })
+      await dispatch('sync', { forceClientState: true }).then((syncDiffLog) => {
```
Comment (gibkigonzo) [inline core/modules/cart/store/actions/itemActions.ts]: Can you use only async/await here? Lets not mix Promise with async/await. I think this should also work:
```
const syncDiffLog = await dispatch('sync', { forceClientState: true })
if (!syncDiffLog.isEmpty()) {
  diffLog.merge(syncDiffLog)
}
```

File: core/modules/cart/store/actions/itemActions.ts [hunk 2]
```diff
@@ -80,9 +80,18 @@ const itemActions = {
...
+    if (newDiffLog !== undefined) {
+      diffLog.merge(newDiffLog)
+    }
+
     if (getters.isCartSyncEnabled && getters.isCartConnected && !forceServerSilence) {
-      return dispatch('sync', { forceClientState: true })
+      const syncDiffLog = await dispatch('sync', { forceClientState: true })
+
+      if (!syncDiffLog.isEmpty()) {
+        diffLog.merge(syncDiffLog)
```
Comment (juho-jaakkola) [inline core/modules/cart/store/actions/itemActions.ts]: Make sure that all these `.merge()` call make sense, as I'm not that familiar with the cart implementation.
