### PR TITLE
Fix loading bestsellers

### LINKED ISSUE #3454: Optimize the `RouterManager.addRoutes`
## What is the motivation for adding / enhancing this feature?

Related to: #3443 

The goal: to reduce the number of times the router beforeEach hooks are run

1. @grimasod to optimize this route registration, going down to one and only `router.addRoutes` call I belive we need just to implement a `RouterManager.routeQueue[]` where `RouteManager.addRoutes` Has new optional argument `useRouteQueue=False`  calls are adding the routes and then the method `RouteManager.registerRoutes` or `RouteManager.flushRouteQueue` which is doing the real registration; this method should be called after all the theme and module routes were registered. We need to change all the core calls to `Router.addRoutes` to set the `useRouteQueue=true`. The default value would be `false for backward compatibility + the calls made after the queue was flushed

2. @grimasod you’re probably right about the multistore route registration but probably: a) just for CSR (as you said for SEO and language switching features we need to have the server side links for other lang versions); b) based on the `storeCode` - we always know the current store code because it’s being guessed on URL/Header/Host before modules were registered. So knowing the `currentStoreView` we can register only the right set of routes (if they’re different from the default routes) - so for default there would be single route registration, for any other lang version probably 2 calls but not 3,4,10 ...

### PR DESCRIPTION
**Pull request by andrzejewsky**
### Related issues
closes #3454

### Short description and why it's useful
It solves the problem with disappearing bestsellers mentioned in https://github.com/DivanteLtd/vue-storefront/pull/3540

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: core/pages/PageNotFound.js [hunk 1]
```diff
@@ -1,32 +0,0 @@
-import { prepareQuery } from '@vue-storefront/core/modules/catalog/queries/common'
```
Comment (patzick) [inline core/pages/PageNotFound.js]: we shouldn't remove this file now, leave it for backward compatibility like the rest of core pages, but just remove dependency from PageNotFound.vue

File: src/themes/default/store/homepage.ts [hunk 2]
```diff
@@ -19,16 +20,31 @@ export const homepageStore = {
         { products: newProductsResult.items
         }, { root: true })
       commit('SET_NEW_COLLECTION', configuredProducts)
+    },
+    async fetchBestsellers ({ commit, dispatch }) {
```
Comment (patzick) [inline src/themes/default/store/homepage.ts]: as we established some time ago, when we fetch and change state, then methods should be called `load...` when just fetching and not mutating state, then `fetch...`
```suggestion
    async loadBestsellers ({ commit, dispatch }) {
```
