### PR TITLE
Bugfix/3077

### LINKED ISSUE #3077: Categories disappears when user is redirected to error page
## Steps to reproduce the issue
1. Go to https://next.storefrontcloud.io/error
2. come back to Home page
3. Press hamburger menu

## Current behavior
Categories disappears when user is redirected to error page.
error_page

## Expected behavior
All available categories should be displayed in hamburger menu

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by pkarw**
### Related issues

closes #3077

### Short description and why it's useful

Error page - back button replaced with <a href to do the full page reload in order to make sure we've preloaded all necessary data

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ ] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

File: src/themes/default/components/core/blocks/Header/MinimalHeader.vue [hunk 1]
```diff
@@ -9,7 +9,9 @@
           <div class="col-sm-4 col-xs-2 middle-xs">
             <div>
               <template>
-                <return-icon class="p15 icon bg-cl-secondary pointer" to="/" />
+                <a class="inline-flex brdr-none p15 icon bg-cl-secondary pointer" href="/" data-testid="returnButton">
```
Comment (patzick) [inline src/themes/default/components/core/blocks/Header/MinimalHeader.vue]:
```suggestion
                <router-link class="inline-flex brdr-none p15 icon bg-cl-secondary pointer" to="/" data-testid="returnButton">
```

File: src/themes/default/components/core/blocks/Header/MinimalHeader.vue [hunk 2]
```diff
@@ -9,7 +9,9 @@
...
+                  <i class="material-icons">keyboard_backspace</i>
+                </a>
```
Comment (patzick) [inline src/themes/default/components/core/blocks/Header/MinimalHeader.vue]:
```suggestion
                </router-link>
```

File: src/themes/default/components/core/blocks/Header/MinimalHeader.vue (hunk 1 above)
Comment (pkarw) [reply src/themes/default/components/core/blocks/Header/MinimalHeader.vue]: We need full page reload. We shouldn't use the router.
