### PR TITLE
Bugfix/trigger app mount in before resolve - 1.11

### LINKED ISSUE #3669: Vue Production Mode: DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
Related issues: #3190, #2216, #1642 
When reloading a category page, I get the following error in my console: 
```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```

This is not really a bug for the releases listed below, since I can't reproduce the error there. I've seen this issue occurred a couple of times before and I want to find out what's happening there. Note that I'm already running the latest VSF version 1.10.3. Also this issue only occurs when the frontend is in production mode, in dev mode everything works.
The most strange thing is, I could "fix" the error by wrapping my category content inside another `<div>` element in the `src/themes/guf/pages/Category.vue` component:
```vue
<template>
  <div id="category">
    <!-- This div is needed to fix #1681. -->
    <div>
    ...
    content
    ...
    </div>
  </div>
</template>
```

Maybe someone can give me a hint of what could be happening here and why I get the error.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 77
- OS: Mac OS
- Node: v10.16.3

### PR DESCRIPTION
**Pull request by gibkigonzo**
### Related issues

closes #3669

### Short description and why it's useful

Similar to https://github.com/DivanteLtd/vue-storefront/pull/3820 but for 1.11

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: core/client-entry.ts [hunk 1]
```diff
@@ -116,6 +110,11 @@ const invokeClientEntry = async () => {
         }
       }))
     })
+    // if route is dispatched and there is no pending in router history
+    // if there is stil pending then 'beforeResolve' will handle app mount, otherwise 'beforeResolve' will not trigger
+    if (RouterManager.isRouteDispatched() && !(router as any).history.pending) {
+      app.$mount('#app')
+    }
```
Comment (pkarw) [inline core/client-entry.ts]: I guess it would be better to mix this edge case handler with the main condition (line 75) into single one. It will be much easier to understand how it exactly works

Comment (gibkigonzo) [reply core/client-entry.ts]: I made update :) Also moved if in onReady callback on top of it.
