### PR TITLE
Bugfix/qa fixes

### LINKED ISSUE #3093: Product page refactoring for theme 2.0
This is the initial plan to refactor the `Product.vue` page accordingly to #2696 and after the initial learnings we got from the `Category.vue` refactoring (#2890)

The goal is to prepare the `Product.vue` for Theme 2.0 - based on Storefront UI but without dramatic changes, keeping the business logic as is (it's very important assumption) and share it between `product` and `product-next` modules. The same time: improving the Vuex readability, preparing the Product page data interface for the 2.0

Stage 1: to be finished till end of July (preferred date: 3rd week of July)

- [ ] Create the `product-next` module for the consistency with `category-next` - use only those new one’s in the new Product.vue and Category.vue
- [ ] We should re-use as much the original logic of `product` module as we can: via helpers or just via importing the actions directly from the old module (doing that way we don’t have to create additional dependencies and can just do like: `import { list } from `@vue-storefront/store/modules/product/actions`
- [ ] Add suitable getters with the proper naming convention -and don’t use the state directly in the theme (just only thru getters)
- [ ] We don’t touch the business logic: `product/helpers` and the actions like `setupBreadcrumbs`, `setupAssociated`, actions related with bundle etc. Maybe just some minor refactoring like:
    - [ ] avoiding state mutations directly in actions (move to mutations)
    - [ ] remove `rootStore` references,
    - [ ] limit the logic based on events
- Don’t change the state much - to keep the single code base with product 1.0 module as far as we can:
    - [ ] we must keep `current`, `original`, `parent`
    - [ ] we must keep `current_bundle_options`, `current_custom_options`, `custom_options_validators`
    - [ ] we can remove (from both - original and new module): `productLoadStart`, `productLoadPromise`, `productGallery` (or if not, rename it to keep the convention which is `under_scored`)
    - [ ] remove `color` and `size` from `current_options` - change the theme to not access this property ditrectly but via getter
    - [ ] we can remove `list` -> but we must refactor the action `product/list` (extract to helper which returns the data + mutate the state after helper is executed in the original `product/list`; in the `product-next/list` (or whatever different name it will have) we can remove this state property as the list ist now in the category)
- Rename getters to the proper naming convention:
    - [ ] `getParentProduct`,
    - [ ] `getCurrentProduct`
    - [ ] `getCurrentProductConfiguration`
    - [ ] `getOriginalProduct`
    - [ ] `getCurrentProductOptions`
    - [ ] `getCurrentProductGallery`
    - [ ] `getCurrenntProductBreadcrumbs`
    - ...
- Refactor Product.vue + remove the `core/pages/Product.js` dependency
    - [ ] map getters with the right getters- https://github.com/DivanteLtd/vue-storefront/blob/70543b3cfa379971220f6514348fe0386a108878/core/pages/Product.js#L25
    - [ ] `attributesByCode` and `attributesByid` seems to not being used anymore and can be removed
    - [ ] shall we have `this.product` or `this.getProduct` (as getter suggest)?
    - [ ] `productName`, `productId` - should be probable replaced with just `product.name` and `productid` in the theme
    - [ ] `customAttributes` ->replaced with vex getter `getCurrentProductCustomAttributes` or just `getCustomAttributes` mapped to `custom_attributes` (as it’s related to the page context only)
    - [ ] Wishlist and Compare should be moved to smart components - the one’s that uses the Vue to perform the logic, but product page shouldn’t be aware of them at all
    - [ ] `isOptionAvailable` could be moved to helper (called just from theme) or can stay here
    - [ ] `onAfterCustomOptionsChanged`, `onAfterBundleOptionsChanged` logic - to be moved to Vuex handler
    - [ ] `onStateCheck` to be removed - the parent check moved to the Vuex
    - [ ] check when `onAfterPriceUpdate` is called (tier prices probably) and check if we can remove it (probably we can move it to vuex + modify tier prices to call this vex action instead)
    - [ ] Not sure if we can move `onAfterFilterChanged` to vex as it replaces parts of url but probably we can
    - [ ] Remove `onUserPricesRefreshed` - I mean call `asyncData` or other vex method instead
- Refactor the `product/actions` and `product/helpers`
    - [ ] replace `state` read operations with getters
    - [ ] replace `state` write operations with mutations
    - [ ] Extract network call from `syncPlatformPricesOver` to helper and then data resolver - remove the `callback_event` (it’s not used)
    - [ ] In the new module `product-next` remove the `setCurrentProduct` and `selectDefaultVariant` from `product-next/single` or its equivalent - the logic of `product-single` should be shared between old and new product modules helper or import; old action should emulate these parameters new one - should just return product data (setting current product should be in different vex action - related to the product page only)
    - [ ] `product/list` should not `updateState` - i mean the new version should not update the state, just return the final data + do caching the `category-next` current call to `product/list` should be replaced with the new method
    - [ ] `related`, `setCurrentOption`, `setCustomOptions`  and `setCurrentErrors` are not used and can be removed
    - [ ] `fetch` and `fetchAsync` should be merged into one call `loadProduct` or `fetchProduct` that will be used in the `Product.vue`

### PR DESCRIPTION
**Pull request by patzick**
### Related issues

closes #3093, #3387

### Short description and why it's useful

No changelog is required, all features are already added, these are QA improvements

- save scroll position on same page (ex change filters on category page)
- productPageVisited hook
- fix labels on product page
- fixed blocked addToCart button in offline mode
- fixed blocked addToCart button for bundle product
- changed duplicated mutation name

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### CODE REVIEW

File: src/themes/default/pages/Product.vue [hunk 1]
```diff
@@ -350,17 +352,24 @@ export default {
     getInputName () {
       if (this.isSimpleOrConfigurable && !this.isProductLoading) { return this.$i18n.t('Quantity available', { qty: this.quantity }) }
       return this.$i18n.t('Quantity')
+    },
+    isAddToCartDisabled () {
+      return (!this.$v.getCurrentProduct.qty.minValue || !this.$v.getCurrentProduct.qty.maxValue || !this.$v.getCurrentProduct.qty.numeric) || (!this.quantity && this.isSimpleOrConfigurable && !this.isProductLoading)
```
Comment (andrzejewsky) [inline src/themes/default/pages/Product.vue]: maybe use here few regular `if` statements because this one inline if is a bit hard to read.

Comment (patzick) [reply src/themes/default/pages/Product.vue]: sure, I just moved it here from Html, but I think it could also be something like
```suggestion
      return this.$v.$invalid || (!this.quantity && this.isSimpleOrConfigurable && !this.isProductLoading)
```
I'll short it

Comment (patzick) [reply src/themes/default/pages/Product.vue]: done :)

File: src/themes/default/pages/Product.vue [hunk 2]
```diff
@@ -350,17 +352,24 @@ export default {
...
     }
   },
   created () {
     this.getQuantity()
   },
-  mounted () {
-    this.$store.dispatch('recently-viewed/addItem', this.getCurrentProduct)
+  async mounted () {
+    await this.$store.dispatch('recently-viewed/addItem', this.getCurrentProduct)
+    await this.$store.dispatch('attribute/list', { // load filter attributes for this specific category
```
Comment (pkarw) [inline src/themes/default/pages/Product.vue]: Wasn’t it called in product/fetch? I bet it was :) wondering why there’s a need to call it in here? More over mounted() is not being called while clicking between recommended products (not switching the routes)

**Comment by patzick** [comment]
fixes #3597 also
