### PR TITLE
Sending shipping address to the shipping-info endpoint

### LINKED ISSUE #2965: shipping address whole object not sent in checkout's shipping-information request
## Current behavior
When updating address in checkout, only countryId field is sent in request payload.

## Expected behavior
Some systems may need whole address object to be sent to calculate totals correctly. When updating address in checkout, whole address object should be sent to the server.

## Steps to reproduce the issue
1. Go to checkout
2. Go to shipping step and update the address
3. Only countryId is sent with the shipping-information payload 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

### PR DESCRIPTION
**Pull request by andrzejewsky**
### Related issues
closes #2965

### Short description and why it's useful
It adds a sending more information about the shipping to the `shipping-information` endpoint as some systems may needs more data to calculate totals etc.

### Which environment this relates to
- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by pkarw** [comment]
Cool! What are the next steps here?

**Comment by andrzejewsky** [comment]
@pkarw I have to check if everything works properly (it works for the first sight), add some unit tests for created helpers and maybe I'll be able to send more address field, because not all of them are accepted by backend (probably magento).

**Comment by pkarw** [comment]
Cool, looking forward for your sight

**Comment by andrzejewsky** [comment]
@pkarw it's ready 🎉

**Comment by pkarw** [comment]
Nice one!

File: core/modules/cart/helpers/createMethodsData.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
+import ShippingDetails from '@vue-storefront/core/modules/checkout/types/ShippingDetails'
+import { ShippingMethodsData } from '@vue-storefront/core/modules/cart/types/ShippingMethodsData'
+
+const getShipping = (shippingMethods: any[]) => {
```
Comment (patzick) [inline core/modules/cart/helpers/createMethodsData.ts]: it would be nice to have real shippingMethod type instead of any, also name is not that clear
```suggestion
const getDefaultShippingMethod = (shippingMethods: any[] = []) => {
```

File: core/modules/cart/helpers/createMethodsData.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+  const shipping = shippingMethods && Array.isArray(shippingMethods) ? shippingMethods.find(item => item.default && !item.offline) : null
```
Comment (patzick) [inline core/modules/cart/helpers/createMethodsData.ts]: we know it's an array, we provided default argument value, find returns null 
```suggestion
  const onlineShippingMethods = shippingMethods.filter(shippingMethod => !shippingMethod.offline)
  if (!onlineShippingMethods.length) return
  return onlineShippingMethods.find(shippingMethod => !!shippingMethod.default) || onlineShippingMethods[0]
```

and rest of this method can be removed then

File: core/modules/cart/helpers/createMethodsData.ts [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+
+  if (!shipping && shippingMethods && shippingMethods.length > 0) {
+    return shippingMethods.find(item => !item.offline)
+  }
+
+  return shipping
+}
+
+const getPayments = (paymentMethods: any[]) => {
```
Comment (patzick) [inline core/modules/cart/helpers/createMethodsData.ts]: same like with shipping, with name, default value and typing
```suggestion
const getDefaultPaymentMethod = (paymentMethods: any[] = []) => {
```

File: core/modules/cart/helpers/createMethodsData.ts [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+  const payment = paymentMethods && Array.isArray(paymentMethods) ? paymentMethods.find(item => item.default) : null
```
Comment (patzick) [inline core/modules/cart/helpers/createMethodsData.ts]:
```suggestion
  if (!paymentMethods || !paymentMethods.length) return
  return paymentMethods.find(item => item.default) || paymentMethods[0]
```
and rest of it can be removed

File: core/modules/cart/types/ShippingMethodsData.ts [hunk 5]
```diff
@@ -0,0 +1,15 @@
+export interface ShippingInfoAddress {
```
Comment (patzick) [inline core/modules/cart/types/ShippingMethodsData.ts]:
```suggestion
export interface ShippingAddress {
```

File: core/modules/cart/types/ShippingMethodsData.ts [hunk 6]
```diff
@@ -0,0 +1,15 @@
...
+  firstname: string,
+  lastname: string,
+  city: string,
+  postcode: string,
+  street: string[]
+}
+
+export interface ShippingMethodsData {
```
Comment (patzick) [inline core/modules/cart/types/ShippingMethodsData.ts]:
```suggestion
export interface OrderShippingDetails {
```
or something a bit more self explaining

File: core/modules/cart/helpers/createMethodsData.ts [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+
+  if (!payment && paymentMethods && paymentMethods.length > 0) {
+    return paymentMethods[0]
+  }
+
+  return payment
+}
+
+const createMethodsData = (shippingDetails: ShippingDetails, shippingMethods: any[], paymentMethods: any[], defaultCountry: string): ShippingMethodsData => {
```
Comment (patzick) [inline core/modules/cart/helpers/createMethodsData.ts]: name of method is not saying what exactly this is and where should we use it, would be nice to change it somehow.
Also it's a good practice to provide default values and take destructured object as params :)

**Comment by pkarw** [comment]
@andrzejewsky are all the changes requested by @patzick already done?

**Comment by andrzejewsky** [comment]
@pkarw yeah, just finished with applying all of them

**Comment by andrzejewsky** [comment]
Guys, any update about that? Could we merge it or is there something else to do? I'm asking because it affects the `actions` of the `cart` module while I've been refactoring it recently, so would be nice to merge it before I start refactor `syncTotals`.

**Comment by pkarw** [comment]
It's fine with me. Should I merge it in now @andrzejewsky?

**Comment by andrzejewsky** [comment]
@pkarw yes, you can merge it :)

**Comment by pkarw** [comment]
Done :)

**Comment by alinadivante** [comment]
@andrzejewsky Should there be two `information-shipping` requests?
Because when I go to Checkout I have two the same requests with different payloads.

One with the following request payload (same as in Demo version):
` 
{,…}
addressInformation: {shippingAddress: {countryId: "PL"}, shippingCarrierCode: "flatrate", shippingMethodCode: "flatrate"}
shippingAddress: {countryId: "PL"}
countryId: "PL"
shippingCarrierCode: "flatrate"
shippingMethodCode: "flatrate" 
`

and the second (which I just expected, with more data):

`{addressInformation: {,…}}
addressInformation: {,…}
shippingAddress: {countryId: "PA", firstname: "Ali", lastname: "Doe", city: "Wroclove", postcode: "00-000",…}
city: "Wroclove"
countryId: "PA"
firstname: "Ali"
lastname: "Doe"
postcode: "00-000"
street: ["my name"]
0: "my name"
shippingCarrierCode: "flatrate"
shippingMethodCode: "flatrate"`

is this second request not enough?

**And to confirm:** 

I have to change the Country during updating the address to see new request payload with more data

**Comment by andrzejewsky** [comment]
@alinadivante Ok, I've checked that and it seems like these doubled request occurs even on `next.storefrontcloud.io` so it didn't caused by this PR. However, It's nice to check whether two request are really necessary. I'll have look at this in the cart PR https://github.com/DivanteLtd/vue-storefront/pull/3317 because it's related.

**Comment by alinadivante** [comment]
ok, thanks @andrzejewsky 
So I accept  this one :) 
Shipping address with more data are sent to the shipping-info endpoint 👌
