### PR TITLE
Fix adding products with custom options

### LINKED ISSUE #3597: Problem with custom options
## Current behavior
I'm unable to add bundle type product to cart.

## Expected behavior
I should be able to see bundle type product price and add it to cart. 

## Steps to reproduce the issue

Visit: https://test.storefrontcloud.io/gear/gear-3/sprite-yoga-companion-kit-45.html
Try to add the product to cart.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information

There are minor differences in API response for this product between "test." and "demo.":

https://test.storefrontcloud.io/api/catalog/vue_storefront_catalog/product/_search?q=sku:24-WG080

https://demo.storefrontcloud.io/api/catalog/vue_storefront_catalog/product/_search?q=sku:24-WG080

### PR DESCRIPTION
**Pull request by andrzejewsky**
### Related issues
closes #3597

### Which environment this relates to
- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: core/modules/cart/store/actions/mergeActions.ts [hunk 1]
```diff
@@ -150,7 +150,10 @@ const mergeActions = {
     }
 
     const productToAdd = await dispatch('getProductVariant', { serverItem })
-    dispatch('addItem', { productToAdd, forceServerSilence: true })
+
+    if (productToAdd) {
+      dispatch('addItem', { productToAdd, forceServerSilence: true })
+    }
```
Comment (pkarw) [inline core/modules/cart/store/actions/mergeActions.ts]: shouldn't we add a notification to difflog that product wasn't found?
