### PR TITLE
Bugfix/body no-scroll behavior for iOS

### LINKED ISSUE #3363: [iOS] Page is scrolled when scrolling the side menu.
## Current behavior
On iOS devices - the page is scrolled when scrolling the side menu.

ios_scrolling

## Expected behavior
Prevent page scrolling when Sidemenu is open.

## Steps to reproduce the problem
1. Go to https://test.storefrontcloud.io/ on the iPad
2. Open the searchbar and enter "top"
3. Scroll the results in the side menu

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by przspa**
### Related issues

closes #3363

### Short description and why it's useful

I added and implemented body-scroll-lock package, because safari doesn't support css lock scroll. https://bundlephobia.com/result?p=body-scroll-lock@2.6.4

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

File: src/themes/default/components/core/Modal.vue [hunk 1]
```diff
@@ -73,6 +83,9 @@ export default {
     this.$bus.$on('modal-toggle', this.onToggle)
     this.$bus.$on('modal-show', this.onShow)
     this.$bus.$on('modal-hide', this.onHide)
+  },
+  mounted () {
```
Comment (patzick) [inline src/themes/default/components/core/Modal.vue]: unnecessary mounted block

**Comment by alinadivante** [comment]
@przspa now I can't scroll cart, wishlist and sidebar-menu (for searchbar works fine)
