### PR TITLE
Fixes #3385 - invalid Discount code handling

### LINKED ISSUE #3385: Invalid Discount code handling error
## Current behavior

An invalid Discount code results in an error notification emitted from the task handler, with the error message coming from the API / Backend. The error is not returned to the calling function, so there is not opportunity to handle it in the theme. The default theme has code for handling this situation, but it never runs.

## Expected behavior

This should be handled by the theme, as it was before v1.10. The theme can display a user-friendly "warning" type notification. The warning text is already included in the language files.

## Steps to reproduce the issue

- Go to https://demo.storefrontcloud.io/
- Add an item to the cart, if empty
- Click on the Microcart icon to open the Microcart sidebar
- Click on "Add a discount code"
- Enter any invalid code, e.g. "1", and click on "Apply"
- A red error notification appears, saying "Coupon code is not valid", which is not included in the language files

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: v1.10

### PR DESCRIPTION
**Pull request by grimasod**
### Related issues

closes #3385

### Short description and why it's useful

Fix issue with invalid Discount code handling

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

File: src/themes/default/components/core/blocks/Microcart/Microcart.vue [hunk 1]
```diff
@@ -178,9 +178,16 @@ export default {
       this.addCouponPressed = false
     },
     setCoupon () {
-      this.applyCoupon(this.couponCode).then(() => {
+      this.applyCoupon(this.couponCode).then((response) => {
```
Comment (patzick) [inline src/themes/default/components/core/blocks/Microcart/Microcart.vue]: to avoid code duplication here we could change method to
```js
  async setCoupon () {
      const couponApplied = await this.applyCoupon(this.couponCode)
      this.addCouponPressed = false
      this.couponCode = ''
      if (!couponApplied) {
        this.$store.dispatch('notification/spawnNotification', {
          type: 'warning',
          message: i18n.t("You've entered an incorrect coupon code. Please try again."),
          action1: { label: i18n.t('OK') }
        })
      }
    },
```

but for this we need to ensure that applyCoupon always returns boolean.

File: core/modules/cart/store/actions.ts [hunk 2]
```diff
@@ -492,12 +492,12 @@ const actions: ActionTree<CartState, RootState> = {
...
           mode: 'cors'
         },
-        silent: false
+        silent: true
       })
       if (task.result === true) {
         dispatch('syncTotals', { forceServerSync: true })
       }
-      return task.result
+      return task
```
Comment (patzick) [inline core/modules/cart/store/actions.ts]: I'd stay here with returning result, but wrapping everything with try-catch block and return false when code is incorrect.

**Comment by grimasod** [comment]
@patzick how about now? I think a try-catch block won't work because the task queue won't throw an error, So I just let it fall through and return false.
@pkarw This is returning to the behaviour up to v1.9. It's still handled by Magento and VS still just displays a message. The only change is that the theme displays a warning, instead of the task queue displaying an error

**Comment by pkarw** [comment]
@grimasod OK, so 1.10.1 is fine
