### PR TITLE
Adjust the loader position on PLP

### LINKED ISSUE #5101: Loader on PLP is misplaced
## Current behavior

image

## Expected behavior

* On the left side the loader should be placed 100px lower
* On the right side there should be loader as well for products

## Steps to reproduce the issue

Enter any category (eg `/c/women`)

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-355) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by TamTran72111**
### Related Issues

closes #5101

### Short Description and Why It's Useful

Adjust the loader position on PLP and add a loader for products as well.

### Screenshots of Visual Changes before/after (if There Are Any)

**Before:**
image

**After:**
image

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: packages/core/nuxt-theme-module/theme/pages/Category.vue [hunk 1]
```diff
@@ -554,4 +556,10 @@ export default {
     width: 100vw;
   }
 }
+.loading {
```
Comment (filrak) [inline packages/core/nuxt-theme-module/theme/pages/Category.vue:559]: it would be more descriptive to put `.loading` in `list` and another `.loading` in `.products` here, wdyt?

Then it's aligned with the CSS hierarchy
image

**Review by filrak — CHANGES_REQUESTED** [review]
Thanks for your input! I've suggested more descriptive naming for CSS classes ;) LMK what do you think and if you think t's right please adjust ;)

**Comment by TamTran72111** [comment]
@filrak, Thanks for your response. For the first loading, I can put it inside `.sidebar`, since it's rendered under `.sidebar`. However, for the second loading, it wraps the `.products`, so I don't think I can put it inside `.products`. If I put `SfLoader` inside `.products`, the loading animation will be prevented by `v-if="!loading"` in the `.products` div. 

This is the image of page layout when rendering loading icons. 
image

Should I put the `.loading` for products inside `.main`, since it can achieve the same visual effect without changing the structure of the page.

**Comment by filrak** [comment]
Yup, sounds good!

**Comment by TamTran72111** [comment]
Hi @filrak , I have updated the CSS.

**Review by filrak — APPROVED** [review]

**Comment by filrak** [comment]
Thank you! Mergin in ;)

If you'd like to contribute more to next but can't find any suitable issues ping me on slack ;)
