### PR TITLE
prevent push defaultStoreCode routes

### LINKED ISSUE #2784: Multistore provide to "Duplicate named routes definition"
## Current behavior
After enabling multistore appears route duplicates.

## Expected behavior
 Duplicates shouldn't appears.

## Steps to reproduce the issue
define defaultStoreCode in config
set multistore to true

## Repository
https://github.com/DivanteLtd/vue-storefront/blob/master/config/default.json#L83

## Can you handle fixing this bug by yourself?
- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
- OS: 4.17.19-1-MANJARO
- Node: v8.12.0
- Code Version: master (1.9 also)

## Additional information
```
[vue-router] Duplicate named routes definition: { name: "virtual-product-amp", path: "/amp/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "bundle-product-amp", path: "/amp/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "simple-product-amp", path: "/amp/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "downloadable-product-amp", path: "/amp/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "grouped-product-amp", path: "/amp/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "configurable-product-amp", path: "/amp/p/:parentSku/:slug/:childSku" }
[vue-router] Duplicate named routes definition: { name: "product-amp", path: "/amp/p/:parentSku/:slug/:childSku" }
[vue-router] Duplicate named routes definition: { name: "category-amp", path: "/amp/c/:slug" }
[vue-router] Duplicate named routes definition: { name: "home", path: "" }
[vue-router] Duplicate named routes definition: { name: "checkout", path: "/checkout" }
[vue-router] Duplicate named routes definition: { name: "legal", path: "/legal" }
[vue-router] Duplicate named routes definition: { name: "privacy", path: "/privacy" }
[vue-router] Duplicate named routes definition: { name: "magazine", path: "/magazine" }
[vue-router] Duplicate named routes definition: { name: "sale", path: "/sale" }
[vue-router] Duplicate named routes definition: { name: "order-tracking", path: "/order-tracking" }
[vue-router] Duplicate named routes definition: { name: "my-account", path: "/my-account" }
[vue-router] Duplicate named routes definition: { name: "my-shipping-details", path: "/my-account/shipping-details" }
[vue-router] Duplicate named routes definition: { name: "my-newsletter", path: "/my-account/newsletter" }
[vue-router] Duplicate named routes definition: { name: "my-orders", path: "/my-account/orders" }
[vue-router] Duplicate named routes definition: { name: "my-order", path: "/my-account/orders/:orderId" }
[vue-router] Duplicate named routes definition: { name: "my-recently-viewed", path: "/my-account/recently-viewed" }
[vue-router] Duplicate named routes definition: { name: "about-us", path: "/about-us" }
[vue-router] Duplicate named routes definition: { name: "customer-service", path: "/customer-service" }
[vue-router] Duplicate named routes definition: { name: "store-locator", path: "/store-locator" }
[vue-router] Duplicate named routes definition: { name: "size-guide", path: "/size-guide" }
[vue-router] Duplicate named routes definition: { name: "gift-card", path: "/gift-card" }
[vue-router] Duplicate named routes definition: { name: "delivery", path: "/delivery" }
[vue-router] Duplicate named routes definition: { name: "returns", path: "/returns" }
[vue-router] Duplicate named routes definition: { name: "order-from-catalog", path: "/order-from-catalog" }
[vue-router] Duplicate named routes definition: { name: "contact", path: "/contact" }
[vue-router] Duplicate named routes definition: { name: "compare", path: "/compare" }
[vue-router] Duplicate named routes definition: { name: "page-not-found", path: "/page-not-found" }
[vue-router] Duplicate named routes definition: { name: "error", path: "/error" }
[vue-router] Duplicate named routes definition: { name: "custom-cms-page", path: "/custom-cms-page" }
[vue-router] Duplicate named routes definition: { name: "cms-block-demo-page-ssr", path: "/cms-block-demo-page-ssr" }
[vue-router] Duplicate named routes definition: { name: "cms-page-sync", path: "/cms-page-sync" }
[vue-router] Duplicate named routes definition: { name: "virtual-product", path: "/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "bundle-product", path: "/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "simple-product", path: "/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "downloadable-product", path: "/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "grouped-product", path: "/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "configurable-product", path: "/p/:parentSku/:slug/:childSku" }
[vue-router] Duplicate named routes definition: { name: "product", path: "/p/:parentSku/:slug/:childSku" }
[vue-router] Duplicate named routes definition: { name: "category", path: "/c/:slug" }
[vue-router] Duplicate named routes definition: { name: "cms-page", path: "/i/:slug" }
[vue-router] Duplicate named routes definition: { name: "virtual-product-amp", path: "/amp/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "bundle-product-amp", path: "/amp/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "simple-product-amp", path: "/amp/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "downloadable-product-amp", path: "/amp/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "grouped-product-amp", path: "/amp/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "configurable-product-amp", path: "/amp/p/:parentSku/:slug/:childSku" }
[vue-router] Duplicate named routes definition: { name: "product-amp", path: "/amp/p/:parentSku/:slug/:childSku" }
[vue-router] Duplicate named routes definition: { name: "category-amp", path: "/amp/c/:slug" }
[vue-router] Duplicate named routes definition: { name: "home", path: "" }
[vue-router] Duplicate named routes definition: { name: "checkout", path: "/checkout" }
[vue-router] Duplicate named routes definition: { name: "legal", path: "/legal" }
[vue-router] Duplicate named routes definition: { name: "privacy", path: "/privacy" }
[vue-router] Duplicate named routes definition: { name: "magazine", path: "/magazine" }
[vue-router] Duplicate named routes definition: { name: "sale", path: "/sale" }
[vue-router] Duplicate named routes definition: { name: "order-tracking", path: "/order-tracking" }
[vue-router] Duplicate named routes definition: { name: "my-account", path: "/my-account" }
[vue-router] Duplicate named routes definition: { name: "my-shipping-details", path: "/my-account/shipping-details" }
[vue-router] Duplicate named routes definition: { name: "my-newsletter", path: "/my-account/newsletter" }
[vue-router] Duplicate named routes definition: { name: "my-orders", path: "/my-account/orders" }
[vue-router] Duplicate named routes definition: { name: "my-order", path: "/my-account/orders/:orderId" }
[vue-router] Duplicate named routes definition: { name: "my-recently-viewed", path: "/my-account/recently-viewed" }
[vue-router] Duplicate named routes definition: { name: "about-us", path: "/about-us" }
[vue-router] Duplicate named routes definition: { name: "customer-service", path: "/customer-service" }
[vue-router] Duplicate named routes definition: { name: "store-locator", path: "/store-locator" }
[vue-router] Duplicate named routes definition: { name: "size-guide", path: "/size-guide" }
[vue-router] Duplicate named routes definition: { name: "gift-card", path: "/gift-card" }
[vue-router] Duplicate named routes definition: { name: "delivery", path: "/delivery" }
[vue-router] Duplicate named routes definition: { name: "returns", path: "/returns" }
[vue-router] Duplicate named routes definition: { name: "order-from-catalog", path: "/order-from-catalog" }
[vue-router] Duplicate named routes definition: { name: "contact", path: "/contact" }
[vue-router] Duplicate named routes definition: { name: "compare", path: "/compare" }
[vue-router] Duplicate named routes definition: { name: "page-not-found", path: "/page-not-found" }
[vue-router] Duplicate named routes definition: { name: "error", path: "/error" }
[vue-router] Duplicate named routes definition: { name: "custom-cms-page", path: "/custom-cms-page" }
[vue-router] Duplicate named routes definition: { name: "cms-block-demo-page-ssr", path: "/cms-block-demo-page-ssr" }
[vue-router] Duplicate named routes definition: { name: "cms-page-sync", path: "/cms-page-sync" }
[vue-router] Duplicate named routes definition: { name: "virtual-product", path: "/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "bundle-product", path: "/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "simple-product", path: "/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "downloadable-product", path: "/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "grouped-product", path: "/p/:parentSku/:slug" }
[vue-router] Duplicate named routes definition: { name: "configurable-product", path: "/p/:parentSku/:slug/:childSku" }
[vue-router] Duplicate named routes definition: { name: "product", path: "/p/:parentSku/:slug/:childSku" }
[vue-router] Duplicate named routes definition: { name: "category", path: "/c/:slug" }
[vue-router] Duplicate named routes definition: { name: "cms-page", path: "/i/:slug" }
```

### PR DESCRIPTION
**Pull request by Devors**
### Related issues
#2784 

closes #2784

### Short description and why it's useful
It's stops duplicating routes.

### Screenshots of visual changes before/after (if there are any)
-

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [X] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ ] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

File: core/lib/multistore.ts [hunk 1]
```diff
@@ -109,9 +109,9 @@ export function localizedRoute (routeObj: Route | string, storeCode: string) {
 }
 
 export function setupMultistoreRoutes (config, router, routes) {
-  if (config.storeViews.mapStoreUrlsFor.length > 0 && config.storeViews.multistore === true) {
+  if (config.storeViews.mapStoreUrlsFor.length > 1 && config.storeViews.multistore === true) {
```
Comment (pkarw) [inline core/lib/multistore.ts]: I think it should be > 0
```suggestion
  if (config.storeViews.mapStoreUrlsFor.length > 0  && config.storeViews.multistore === true) {
```

File: core/lib/multistore.ts [hunk 2]
```diff
@@ -109,9 +109,9 @@ export function localizedRoute (routeObj: Route | string, storeCode: string) {
...
     for (let storeCode of config.storeViews.mapStoreUrlsFor) {
-      if (storeCode) {
+      if (storeCode || (config.defaultStoreCode !== storeCode)) {
```
Comment (pkarw) [inline core/lib/multistore.ts]: Shouldn't it be `&&` instead of `||`?  The `or` condition makes only sence in case `storeCode` is null either empty which probably never occurs in this context
```suggestion
      if (storeCode && (config.defaultStoreCode !== storeCode)) {
```

**Comment by pkarw** [comment]
I've suggested two changes in the CR process.

File: core/lib/multistore.ts (hunk 1 above)
Comment (pkarw) [reply core/lib/multistore.ts]: ... this is because the default URLs are always mapped anyway in the https://github.com/DivanteLtd/vue-storefront/blob/76a75759550ec2b7dd9642eb3b281566c1590dc5/src/themes/default/index.js#L20 - so when there is even one additional `storeCode` to map in the `storeViews.mapStoreUrlsFor` then it should be mapped

File: core/lib/multistore.ts (hunk 2 above)
Comment (Devors) [reply core/lib/multistore.ts]: Yps, it's should be `&&`, I put `||` just for test.

File: core/lib/multistore.ts (hunk 1 above)
Comment (Devors) [reply core/lib/multistore.ts]: thank you @pkarw  for explaining
