### PR TITLE
Replace microdata to json-ld

### LINKED ISSUE #3704: Product Page Schema implementation as JSON-LD
# Summary
[summary]: #summary

Change Schema implementation to JSON-LD

# Motivation
[motivation]: #motivation

Google about [JSON-LD](https://developers.google.com/search/docs/guides/intro-structured-data#markup-formats-and-placement)

`JSON-LD is the recommended format. Google is in the process of adding JSON-LD support for all markup-powered features. The table below lists the exceptions to this. We recommend using JSON-LD where possible.`

It's also more readable beacuse we can find Schema implemented in one place in code not all over it.

# Future possibilities
[future-possibilities]: #future-possibilities

Implement JSON-LD Schema on all app.

### PR DESCRIPTION
**Pull request by Michal-Dziedzinski**
### Related Issues

closes #3704 

### Short Description and Why It's Useful

Replace microdata to json-ld which is the recommended by Google.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gibkigonzo** [comment]
Hey 😄  wdyt about moving all of those functions to separate file as helpers?
We could expose there:
- `export function reviewJsonLd({review})`
- `export function productJsonLd({product, configuration, attributes, storeView})`

and rest keep as local functions: 
- `function getMaterials(material)`

also I think we can now remove `structuredData` and just get `availability` in helper 🤔

File: src/themes/default/pages/Product.vue [hunk 1]
```diff
@@ -336,6 +326,9 @@ export default {
     },
     storeView () {
       return currentStoreView()
+    },
+    getJsonLd () {
+      return productJsonLd(this.getCurrentProduct, this.getCurrentProductConfiguration.color.label, this.getMaterials(this.getCurrentProduct.material), this.$store.state.storeView.i18n.currencyCode)
```
Comment (gibkigonzo) [inline src/themes/default/pages/Product.vue]: one more thing :) Can you also move `getMaterials` from component to helper? It's needed only for `productJsonLd` and if you already pass `this.getCurrentProduct` as argument then you can get material in `productJsonLd`.
So this will be shorter:
`productJsonLd(this.getCurrentProduct, this.getCurrentProductConfiguration.color.label, this.$store.state.storeView.i18n.currencyCode)`

Comment (Michal-Dziedzinski) [reply src/themes/default/pages/Product.vue]: @gibkigonzo you also need `this.getCustomAttributes` to `getMatrials`, so I'm not sure that it is good idea because I need to pass the same number of arguments, wdyt?

**Comment by andrzejewsky** [comment]
@Michal-Dziedzinski Looks really good, one thing - did you test it with some validator ? eg: https://json-ld.org/playground/ (if document generated by product page is correct)

**Comment by Michal-Dziedzinski** [comment]
> @Michal-Dziedzinski Looks really good, one thing - did you test it with some validator ? eg: https://json-ld.org/playground/ (if document generated by product page is correct)

no, but after checking it turned out that I have to add a few fields to the object with reviews, so I added them :)

**Comment by andrzejewsky** [comment]
@Michal-Dziedzinski please resolve conflict here and it will be ready for merge ;)

**Comment by Michal-Dziedzinski** [comment]
@andrzejewsky resolved ;)
