### PR TITLE
trigger app.$mount in beforeResolve

### LINKED ISSUE #3669: Vue Production Mode: DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
Related issues: #3190, #2216, #1642 
When reloading a category page, I get the following error in my console: 
```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```

This is not really a bug for the releases listed below, since I can't reproduce the error there. I've seen this issue occurred a couple of times before and I want to find out what's happening there. Note that I'm already running the latest VSF version 1.10.3. Also this issue only occurs when the frontend is in production mode, in dev mode everything works.
The most strange thing is, I could "fix" the error by wrapping my category content inside another `<div>` element in the `src/themes/guf/pages/Category.vue` component:
```vue
<template>
  <div id="category">
    <!-- This div is needed to fix #1681. -->
    <div>
    ...
    content
    ...
    </div>
  </div>
</template>
```

Maybe someone can give me a hint of what could be happening here and why I get the error.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 77
- OS: Mac OS
- Node: v10.16.3

### PR DESCRIPTION
**Pull request by gibkigonzo**
### Related issues

closes #3669

### Short description and why it's useful

Problem occur because we mount app before async route component is resolved. So we can use `beforeResolve`. As described in vue-router docs it's triggered ["**after all in-component guards and async route components are resolved**"](https://router.vuejs.org/guide/advanced/navigation-guards.html#global-resolve-guards). We only need to check if app is already loaded.

### QA
1. Change in `src/themes/default/router/index.js`
```
const Home = () => import(/* webpackChunkName: "vsf-home" */ 'theme/pages/Home.vue')
```
to
```
const Home = () => new Promise((resolve) => {
  setTimeout(async () => {
    resolve(import(/* webpackChunkName: "vsf-home" */ 'theme/pages/Home.vue'))
  }, 5000)
})
```
This will simulate very long lazy loading.
2. check homepage in dev and prod mode => it should crash in prod and there should be mismatch in dev mode

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: core/client-entry.ts [hunk 1]
```diff
@@ -99,12 +103,9 @@ const invokeClientEntry = async () => {
...
     })
-    // Mounting app
-    if (!RouterManager.isRouteDispatched()) {
-      RouterManager.addDispatchCallback(() => {
-        app.$mount('#app')
-      })
-    } else {
+    // if route is dispatched and there is no pending in router history
+    // if there is stil pending then 'beforeResolve' will handle app mount, otherwise 'beforeResolve' will not trigger
+    if (RouterManager.isRouteDispatched() && !(router as any).history.pending) {
```
Comment (pkarw) [inline core/client-entry.ts]: I guess this should be combined with the condition from the line 68 into single one for devs to make it easier to get what these conditions are doing :)

Comment (gibkigonzo) [reply core/client-entry.ts]: I made update :) Also moved if in onReady callback on top of it.

File: core/client-entry.ts [hunk 2]
```diff
@@ -63,8 +63,22 @@ const invokeClientEntry = async () => {
...
+      !(app as any)._isMounted // it's not mounted before
+
+    if (canBeMounted()) {
+      app.$mount('#app')
+    }
     router.beforeResolve((to, from, next) => {
-      if (!from.name) return next() // do not resolve asyncData on server render - already been done
+      if (!from.name) {
+        next()
+        if (canBeMounted()) {
```
Comment (pkarw) [inline core/client-entry.ts]: shouldn't this be executed before next()?

Comment (gibkigonzo) [reply core/client-entry.ts]: Problem is that vue-router doesn't reveal when it resolve async components in beforeResolve. So I check when `this.pending` is falsy, because it gets null just after enter events are finished ([here](https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L190)). In this [line](https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L185) it adds `this.router.resolveHooks` (beforeResolve) to other enter events. So we need to wait just after beforeResolve is finished and then we have falsy `this.pending`. Best solution would be mounting app after `queue` ends ([here](https://github.com/vuejs/vue-router/blob/dev/src/history/base.js#L143)), but I couldn't find any flag to check this in beforeResolve.

Comment (gibkigonzo) [reply core/client-entry.ts]: I had to keep app mounting in onReady callback because in production version on for example homepage there could be a situation that beforeResolve event is not triggered at all.
