### PR TITLE
Fix/4087

### LINKED ISSUE #4087: Sidebar menu cannot have more than one custom submenu
## Current behavior

The links in the sidebar menu are mostly generated from the root categories, with the possibility of paged navigation to subcategories.

This works fine for categories, but there is a problem with having more than one custom multi-level menu item. The `sub-btn` expects a prop called `id` which, when provided, performs an ElasticSearch lookup for the specified category.

In the default theme, links to[ _My Account_ ](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/SidebarMenu/SidebarMenu.vue#L111)are implemented as a custom menu item, not passing the `id` prop. When having more than one custom menu item in this fashion, clicking on any other menu item shows the submenu for the first item (matching the first menu item that passed its content with a null `id` prop).

Here is an example, where I have a custom menu item. It works fine when the user is logged out, but as soon as My Account links are available, it doesn't go to the right submenu:

## Expected behavior

The sidebar menu should have a feature to properly create custom multi-level menu items.
Instead of providing a null `id` prop, there should be another prop for these custom items.

## Repository

https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/SidebarMenu/SidebarMenu.vue#L111

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [X] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [X] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by themreza**
### Related Issues

closes #4087

### Short Description and Why It's Useful

Allows adding custom non-category sidebar menu items that have their own submenu page.

Note: Since both `SubCategory.vue` and `SubBtn.vue` have an `id` prop, supplying the same `id` attribute when calling them in the same page results in a warning, stating that the same id cannot be reused on multiple HTML elements. This is a false-positive, but it's nice to change the `id` name to something else.

### Screenshots of Visual Changes before/after (if There Are Any)

Before:

After:

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [X] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/themes/default/components/core/blocks/SidebarMenu/SidebarMenu.vue [hunk 1]
```diff
@@ -110,13 +110,15 @@
...
+              id="my-account-links"
               :name="$t('My account')"
               class="bg-cl-transparent brdr-none fs-medium-small"
             />
             <sub-category
               v-if="currentUser"
               :my-account-links="myAccountLinks"
-              :id="'foo'"
+              id="my-account-links"
+              :is-category="false"
```
Comment (gibkigonzo) [inline src/themes/default/components/core/blocks/SidebarMenu/SidebarMenu.vue]: component `SubCategory` doesn't have prop `isCategory`. If you wanted to add it to `SubBtn` then I think we should keep it as `true`, because by default we want to prefetch category.

**Comment by pkarw** [comment]
@themreza can you please change this one thing? :)

**Comment by themreza** [comment]
Sorry for that mix-up and good spot. It's now fixed :)

File: src/themes/default/components/core/blocks/SidebarMenu/SidebarMenu.vue (hunk 1 above)
Comment (gibkigonzo) [reply src/themes/default/components/core/blocks/SidebarMenu/SidebarMenu.vue]: Ok, now I get it. Thanks for update :)
