### PR TITLE
Home Page: Fixed Header title shown issue even product list is not exist

### LINKED ISSUE #2761: Home Page: Header title displayed if newCollection product list not exists
Header title should be hidden if newCollection product list not exists
There are no products under **Everything New** section but the header is displayed. it shouldn't render id products are not available.

## Current behavior

2019_04_18_Selection_001

## Expected behavior

2019_04_18_Selection_002

## Steps to reproduce the issue

1. Removed products from **Everything New** Section
2. Check only header is displayed

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: Ubuntu
- Node: 10.15.1
- Code Version:

### PR DESCRIPTION
**Pull request by vishal-7037**
### Related issues

closes #2761

### Short description and why it's useful

**Fixed issue:** Header title should be hidden if newCollection product list not exists

### Screenshots of visual changes before/after (if there are any)
**Before Fixed**
2019_04_18_Selection_001

**After Fixed:**
2019_04_18_Selection_002

**After Fixed With Product List:**

2019_04_18_Selection_003

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [X] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [ ] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by filrak** [comment]
Hey! Thanks for the contribution. It looks like you choose `develop` branch as a base therefore it's the only one we can merge your PR in. In the future always use the one that you want to push into as a base.

Thanks for your contribution and welcome in the dev community!

**Comment by pkarw** [comment]
Please just update a changelog - and maybe it would Ben nice to check if everythingNew isn’t a null in the first place just to make sure it has length property :)

File: src/themes/default/pages/Home.vue [hunk 1]
```diff
@@ -4,7 +4,7 @@
 
     <promoted-offers/>
 
-    <section class="new-collection container px15">
+    <section class="new-collection container px15" v-if="everythingNewCollection.length">
```
Comment (pkarw) [inline src/themes/default/pages/Home.vue]:
```suggestion
    <section class="new-collection container px15" v-if="everythingNewCollection && everythingNewCollection.length">
```
