### PR TITLE
2730 checkboxes

### LINKED ISSUE #2730: Incorrect working of checkboxes in checkout
## Current behavior

After marking the "ship to my default address" or "copy address data from shipping" checkbox, the form is not filled in with data, whereas after unmarking checkboxes - forms are filled in.
incorrectoperationofcheckboxe

## Expected behavior
After selecting the "ship to my default address" or "copy address data from shipping" checkbox, the appropriate form is filled with data.

## Steps to reproduce the issue

1. Go to https://test.storefrontcloud.io
2. Add any product to the cart
3. Go to checkout
4. Login to your account (which has memorized shipping details)
5. Continue to shipping
6. Mark checkbox "ship to my default address" 
7. Unmark checkbox "ship to my default address" 
8. Continue to payment
9. Mark chceckbox "copy address data from shipping"
10. Unmark checkbox "copy address data from shipping"

## Can you handle fixing this bug by yourself?
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Windows 10

## Additional information

This problem only appears on the environment https://test.storefrontcloud.io, does not appear on next and demo.

### PR DESCRIPTION
**Pull request by dimasch**
### Related issues
closes #2730

### Short description and why it's useful
For new checkbox component need use `v-model` instead click handler.

### Which environment this relates to
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/Upgrade%20notes.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and currently important rules acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

File: core/modules/checkout/components/Payment.ts [hunk 1]
```diff
@@ -59,6 +59,16 @@ export const Payment = {
       handler () {
         this.useShippingAddress()
       }
+    },
+    sendToBillingAddress: {
+      handler () {
+        this.useBillingAddress()
+      }
+    },
+    generateInvoice: {
```
Comment (dimasch) [inline core/modules/checkout/components/Payment.ts]: For this one `click` removed in previous PRs.
