### PR TITLE
Missing coupon code after login or registering

### LINKED ISSUE #3153: Applied discount code is lost when logging in / creating account / placing an order with account creation
## Current behavior
When a user logs in after applying a discount code ("mmtest") in the cart (e.g. log-in on checkout page), the discount code is no longer applied.
Moreover, if the user chooses to create an account during checkout, the order is placed without the applied discount code.

## Expected behavior
Discount code is kept applied when user logs in or creates an account.

## Steps to reproduce the issue
1. Put item into cart and apply discount code "mmtest"
2a. Create or log into existing account -> discount no longer applied 
2b. Create account during checkout -> order is placed without discount

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

### PR DESCRIPTION
**Pull request by andrzejewsky**
### Related issues
closes #3153

### Short description and why it's useful
It fixes the disappearing of already applied coupon code when user has just logged in

### Which environment this relates to
- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog

- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing VS sites with this new feature

### Contribution and currently important rules acceptance
- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)
- [x] I read the [TypeScript Action Plan](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/TypeScript%20Action%20Plan.md) and adjusted my PR according to it
- [x] I read about [Vue Storefront Modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) and I am aware that every new feature should be a module

### CODE REVIEW

**Comment by andrzejewsky** [comment]
Basically it's a bit tricky because everything does work when we have "fresh" browser (no cache, local storage), but when we had some orders recently, this coupon doesn't apply correctly - from the UI everything looks good but it seems like this order doesn't have that coupon applied.

I've been tying to figure out why it happens and it seems like this "if" is responsible for that:
```
    if (!config.cart.bypassCartLoaderForAuthorizedUsers || (Date.now() - lastCartBypassTs) >= (1000 * 60 * 24)) {
      await dispatch('connect', { guestCart: false })
    }
```
It turned out if I apply the coupon (dispatching `applyCoupon`) without dispatching the `connect` beforehand, the order will be placed without a coupon (while on the UI it actually does). Maybe the cart ids are different? and there is some mismatch between client cart and the backend cart? Any thoughts?

**Comment by pkarw** [comment]
@andrzejewsky good point. This condition is a work around for the issues we had with placing orders; previously orders had been passed to magento asynchronously - so it could be lik 2-3min delay between placing order and finishing it (passing to magento) it has been done by `o2m` queue in `vue-storefront-api`. Becuase of that there was a bypassing mechanism off creagint new guest cart ID if the new cart is needed shortly after last order. Because the `api/cart/create` had been returning the `cart-id` related to not-closed-quote which caused a lot o  sync issues (bc. the quote was then closed in the background without any notify)

Currently, there are a direct sync mode`config.orders.directBackendSync` set to `true` be default and the orders are passed over to Magento immediately; so using the `user-assigned` `cart_id` is now safe.

So, if this solves this issue please just add the check to enable this workaround only if  `!config.orders.directBackendSync`

File: core/modules/user/store/actions.ts [hunk 1]
```diff
@@ -271,10 +271,10 @@ const actions: ActionTree<UserState, RootState> = {
       }
     }
   },
-  sessionAfterAuthorized ({ dispatch }, { refresh = onlineHelper.isOnline, useCache = true }) {
+  async sessionAfterAuthorized ({ dispatch }, { refresh = onlineHelper.isOnline, useCache = true }) {
     Logger.info('User session authorised ', 'user')()
-    dispatch('me', { refresh, useCache })
-    dispatch('getOrdersHistory', { refresh, useCache })
+    await dispatch('me', { refresh, useCache })
```
Comment (pkarw) [inline core/modules/user/store/actions.ts]: shouldn't it be executed in parallel without await?

Comment (andrzejewsky) [reply core/modules/user/store/actions.ts]: not really because `me` triggers other actions, such us `cart/authorize` I remember I had problem with that, because that `cart/authorise` must be triggered before making the order... but let me check again, maybe it's really unnecessary here.

**Comment by andrzejewsky** [comment]
@pkarw when it comes to `config.orders.directBackendSync` - I've already made this, https://github.com/DivanteLtd/vue-storefront/pull/3301/files#diff-2101c92c40c144e3e56fb400ac211e3dR525 usually I squash the commits (it's cleaner) maybe that's why you haven't noticed that change for the first sight

**Comment by pkarw** [comment]
Cool! Thanks, I missed this condition. It's fine

**Comment by ArturDivante** [comment]
Looks like problem is fixed. Tested for both login and account register - used discount is correctly applied :)
