### PR TITLE
Default placeholder not displayed on product page

### LINKED ISSUE #5087: Default placeholder is not displayed on Product page
## Current behavior
If the product.image and product.configurable_children.image is empty, then on the category page the default placeholder is displayed in the place of the product image but on the Product page, the placeholder is not displayed.

## Expected behavior
If there is no image in the Product Gallery then the default placeholder should be displayed on the Product page.

## Steps to reproduce the issue
1. Click on the product on the category page which consists of a placeholder.
2. You will see a blank Product Gallery.

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by ymaheshwari1**
### Related Issues
#5087 

closes #5087 

### Short Description and Why It's Useful
If a product does not contain an image, then on the product page default placeholder should be displayed, but currently, the product gallery is blank.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: core/modules/catalog/helpers/index.ts [hunk 1]
```diff
@@ -112,6 +112,13 @@ export function attributeImages (product) {
       }
     }
   }
+  if (attributeImages.length <= 0) {
```
Comment (Fifciu) [inline core/modules/catalog/helpers/index.ts:115]: Just use `!attributeImages.length`

File: core/modules/catalog/helpers/index.ts [hunk 2]
```diff
@@ -112,6 +112,13 @@ export function attributeImages (product) {
...
+    attributeImages.push({
+      'src': getThumbnailPath(product['image'], config.products.gallery.width, config.products.gallery.height),
```
Comment (Fifciu) [inline core/modules/catalog/helpers/index.ts:117]: Let's replace `'src'` with just `src` and `product['image']` with just `product.image`, same for these 2 below

Comment (Fifciu) [reply core/modules/catalog/helpers/index.ts:117]: This PR is also related to your other one: https://github.com/DivanteLtd/vue-storefront/pull/5091
What do you think about merging them in one and getting rid of hardcoded sizes in every place inside `attributeImages`? (not only in if (product[attribute]))

**Review by Fifciu — CHANGES_REQUESTED** [review]

File: core/modules/catalog/helpers/index.ts (hunk 1 above)
Comment (ymaheshwari1) [reply core/modules/catalog/helpers/index.ts:115]: Ok, I'll update this.

File: core/modules/catalog/helpers/index.ts (hunk 2 above)
Comment (ymaheshwari1) [reply core/modules/catalog/helpers/index.ts:117]: Sure, will do the changes.

Comment (ymaheshwari1) [reply core/modules/catalog/helpers/index.ts]: @Fifciu I have updated the code.

**Review by Fifciu — APPROVED** [review]
Great, thanks!

File: core/modules/catalog/helpers/getProductGallery.ts [hunk 3]
```diff
@@ -15,7 +15,7 @@ export default function getProductGallery (product: Product) {
   }
 
   const productGallery = uniqBy(configurableChildrenImages(product).concat(getMediaGallery(product)), 'src')
-    .filter(f => f.src && f.src !== config.images.productPlaceholder)
+    .filter(f => f.src)
```
Comment (gibkigonzo) [inline core/modules/catalog/helpers/getProductGallery.ts:18]: why you removed that?

File: core/modules/catalog/helpers/index.ts [hunk 4]
```diff
@@ -105,13 +105,20 @@ export function attributeImages (product) {
...
+          error: getThumbnailPath(product[attribute], config.products.thumbnails.width, config.products.thumbnails.height)
         })
       }
     }
   }
+  if (!attributeImages.length) {
+    attributeImages.push({
+      src: getThumbnailPath(product.image, config.products.gallery.width, config.products.gallery.height),
+      loading: getThumbnailPath(product.image, config.products.thumbnails.width, config.products.thumbnails.height),
+      error: getThumbnailPath(product.image, config.products.thumbnails.width, config.products.thumbnails.height)
```
Comment (gibkigonzo) [inline core/modules/catalog/helpers/index.ts:119]: If we don't have `product.image` then maybe we should use `config.images.productPlaceholder`?
```
      src: getThumbnailPath(config.images.productPlaceholder, config.products.gallery.width, config.products.gallery.height),
      loading: getThumbnailPath(config.images.productPlaceholder, config.products.thumbnails.width, config.products.thumbnails.height),
      error: getThumbnailPath(config.images.productPlaceholder, config.products.thumbnails.width, config.products.thumbnails.height)
```

Comment (gibkigonzo) [reply core/modules/catalog/helpers/index.ts:119]: Also lets add code to `getProductGallery` because there we build gallery and adding placeholder is last step (we are adding it only if there are no images)

**Review by gibkigonzo — CHANGES_REQUESTED** [review]

File: core/modules/catalog/helpers/getProductGallery.ts (hunk 3 above)
Comment (ymaheshwari1) [reply core/modules/catalog/helpers/getProductGallery.ts:18]: Actually, this condition does not allow a placeholder to be in the productGallery, and hence to add a placeholder in the gallery removed this condition.

File: core/modules/catalog/helpers/index.ts (hunk 4 above)
Comment (ymaheshwari1) [reply core/modules/catalog/helpers/index.ts]: I have updated the code by adding the default placeholder condition to the `getProductGallery` and removing the condition to add the default placeholder in the attributeImages().

@gibkigonzo and @Fifciu Please review.

**Review by gibkigonzo — APPROVED** [review]

File: core/modules/catalog/helpers/index.ts (hunk 4 above)
Comment (gibkigonzo) [reply core/modules/catalog/helpers/index.ts]: looks good for me :+1:

**Review by Fifciu — APPROVED** [review]
